// Generated by swift-openapi-generator, do not modify.
@_spi(Generated) import OpenAPIRuntime
#if os(Linux)
@preconcurrency import struct Foundation.URL
@preconcurrency import struct Foundation.Data
@preconcurrency import struct Foundation.Date
#else
import struct Foundation.URL
import struct Foundation.Data
import struct Foundation.Date
#endif
/// A type that performs HTTP operations defined by the OpenAPI document.
internal protocol APIProtocol: Sendable {
    /// List Milestones
    ///
    /// Retrieves a list of milestones from the specified repository.
    ///
    /// - Remark: HTTP `GET /repos/{owner}/{repo}/milestones`.
    /// - Remark: Generated from `#/paths//repos/{owner}/{repo}/milestones/get(listMilestones)`.
    func listMilestones(_ input: Operations.ListMilestones.Input) async throws -> Operations.ListMilestones.Output
    /// Create a Milestone
    ///
    /// Creates a new milestone in the specified repository.
    ///
    /// - Remark: HTTP `POST /repos/{owner}/{repo}/milestones`.
    /// - Remark: Generated from `#/paths//repos/{owner}/{repo}/milestones/post(createMilestone)`.
    func createMilestone(_ input: Operations.CreateMilestone.Input) async throws -> Operations.CreateMilestone.Output
    /// Get a Milestone
    ///
    /// Retrieves details of a specific milestone.
    ///
    /// - Remark: HTTP `GET /repos/{owner}/{repo}/milestones/{milestone_number}`.
    /// - Remark: Generated from `#/paths//repos/{owner}/{repo}/milestones/{milestone_number}/get(getMilestone)`.
    func getMilestone(_ input: Operations.GetMilestone.Input) async throws -> Operations.GetMilestone.Output
    /// Update a Milestone
    ///
    /// Updates an existing milestone.
    ///
    /// - Remark: HTTP `PATCH /repos/{owner}/{repo}/milestones/{milestone_number}`.
    /// - Remark: Generated from `#/paths//repos/{owner}/{repo}/milestones/{milestone_number}/patch(updateMilestone)`.
    func updateMilestone(_ input: Operations.UpdateMilestone.Input) async throws -> Operations.UpdateMilestone.Output
    /// Delete a Milestone
    ///
    /// Deletes a specific milestone.
    ///
    /// - Remark: HTTP `DELETE /repos/{owner}/{repo}/milestones/{milestone_number}`.
    /// - Remark: Generated from `#/paths//repos/{owner}/{repo}/milestones/{milestone_number}/delete(deleteMilestone)`.
    func deleteMilestone(_ input: Operations.DeleteMilestone.Input) async throws -> Operations.DeleteMilestone.Output
}

/// Convenience overloads for operation inputs.
extension APIProtocol {
    /// List Milestones
    ///
    /// Retrieves a list of milestones from the specified repository.
    ///
    /// - Remark: HTTP `GET /repos/{owner}/{repo}/milestones`.
    /// - Remark: Generated from `#/paths//repos/{owner}/{repo}/milestones/get(listMilestones)`.
    internal func listMilestones(path: Operations.ListMilestones.Input.Path) async throws -> Operations.ListMilestones.Output {
        try await listMilestones(Operations.ListMilestones.Input(path: path))
    }
    /// Create a Milestone
    ///
    /// Creates a new milestone in the specified repository.
    ///
    /// - Remark: HTTP `POST /repos/{owner}/{repo}/milestones`.
    /// - Remark: Generated from `#/paths//repos/{owner}/{repo}/milestones/post(createMilestone)`.
    internal func createMilestone(
        path: Operations.CreateMilestone.Input.Path,
        body: Operations.CreateMilestone.Input.Body
    ) async throws -> Operations.CreateMilestone.Output {
        try await createMilestone(Operations.CreateMilestone.Input(
            path: path,
            body: body
        ))
    }
    /// Get a Milestone
    ///
    /// Retrieves details of a specific milestone.
    ///
    /// - Remark: HTTP `GET /repos/{owner}/{repo}/milestones/{milestone_number}`.
    /// - Remark: Generated from `#/paths//repos/{owner}/{repo}/milestones/{milestone_number}/get(getMilestone)`.
    internal func getMilestone(path: Operations.GetMilestone.Input.Path) async throws -> Operations.GetMilestone.Output {
        try await getMilestone(Operations.GetMilestone.Input(path: path))
    }
    /// Update a Milestone
    ///
    /// Updates an existing milestone.
    ///
    /// - Remark: HTTP `PATCH /repos/{owner}/{repo}/milestones/{milestone_number}`.
    /// - Remark: Generated from `#/paths//repos/{owner}/{repo}/milestones/{milestone_number}/patch(updateMilestone)`.
    internal func updateMilestone(
        path: Operations.UpdateMilestone.Input.Path,
        body: Operations.UpdateMilestone.Input.Body
    ) async throws -> Operations.UpdateMilestone.Output {
        try await updateMilestone(Operations.UpdateMilestone.Input(
            path: path,
            body: body
        ))
    }
    /// Delete a Milestone
    ///
    /// Deletes a specific milestone.
    ///
    /// - Remark: HTTP `DELETE /repos/{owner}/{repo}/milestones/{milestone_number}`.
    /// - Remark: Generated from `#/paths//repos/{owner}/{repo}/milestones/{milestone_number}/delete(deleteMilestone)`.
    internal func deleteMilestone(path: Operations.DeleteMilestone.Input.Path) async throws -> Operations.DeleteMilestone.Output {
        try await deleteMilestone(Operations.DeleteMilestone.Input(path: path))
    }
}

/// Server URLs defined in the OpenAPI document.
internal enum Servers {
    /// Proxy server for GitHub Milestones API.
    internal enum Server1 {
        /// Proxy server for GitHub Milestones API.
        internal static func url() throws -> Foundation.URL {
            try Foundation.URL(
                validatingOpenAPIServerURL: "https://milestones.pm.fountain.coach",
                variables: []
            )
        }
    }
    /// Proxy server for GitHub Milestones API.
    @available(*, deprecated, renamed: "Servers.Server1.url")
    internal static func server1() throws -> Foundation.URL {
        try Foundation.URL(
            validatingOpenAPIServerURL: "https://milestones.pm.fountain.coach",
            variables: []
        )
    }
}

/// Types generated from the components section of the OpenAPI document.
internal enum Components {
    /// Types generated from the `#/components/schemas` section of the OpenAPI document.
    internal enum Schemas {}
    /// Types generated from the `#/components/parameters` section of the OpenAPI document.
    internal enum Parameters {}
    /// Types generated from the `#/components/requestBodies` section of the OpenAPI document.
    internal enum RequestBodies {}
    /// Types generated from the `#/components/responses` section of the OpenAPI document.
    internal enum Responses {}
    /// Types generated from the `#/components/headers` section of the OpenAPI document.
    internal enum Headers {}
}

/// API operations, with input and output types, generated from `#/paths` in the OpenAPI document.
internal enum Operations {
    /// List Milestones
    ///
    /// Retrieves a list of milestones from the specified repository.
    ///
    /// - Remark: HTTP `GET /repos/{owner}/{repo}/milestones`.
    /// - Remark: Generated from `#/paths//repos/{owner}/{repo}/milestones/get(listMilestones)`.
    internal enum ListMilestones {
        internal static let id: Swift.String = "listMilestones"
        internal struct Input: Sendable, Hashable {
            /// - Remark: Generated from `#/paths/repos/{owner}/{repo}/milestones/GET/path`.
            internal struct Path: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/repos/{owner}/{repo}/milestones/GET/path/owner`.
                internal var owner: Swift.String
                /// - Remark: Generated from `#/paths/repos/{owner}/{repo}/milestones/GET/path/repo`.
                internal var repo: Swift.String
                /// Creates a new `Path`.
                ///
                /// - Parameters:
                ///   - owner:
                ///   - repo:
                internal init(
                    owner: Swift.String,
                    repo: Swift.String
                ) {
                    self.owner = owner
                    self.repo = repo
                }
            }
            internal var path: Operations.ListMilestones.Input.Path
            /// Creates a new `Input`.
            ///
            /// - Parameters:
            ///   - path:
            internal init(path: Operations.ListMilestones.Input.Path) {
                self.path = path
            }
        }
        internal enum Output: Sendable, Hashable {
            internal struct Ok: Sendable, Hashable {
                /// Creates a new `Ok`.
                internal init() {}
            }
            /// List of milestones retrieved successfully.
            ///
            /// - Remark: Generated from `#/paths//repos/{owner}/{repo}/milestones/get(listMilestones)/responses/200`.
            ///
            /// HTTP response code: `200 ok`.
            case ok(Operations.ListMilestones.Output.Ok)
            /// List of milestones retrieved successfully.
            ///
            /// - Remark: Generated from `#/paths//repos/{owner}/{repo}/milestones/get(listMilestones)/responses/200`.
            ///
            /// HTTP response code: `200 ok`.
            internal static var ok: Self {
                .ok(.init())
            }
            /// The associated value of the enum case if `self` is `.ok`.
            ///
            /// - Throws: An error if `self` is not `.ok`.
            /// - SeeAlso: `.ok`.
            internal var ok: Operations.ListMilestones.Output.Ok {
                get throws {
                    switch self {
                    case let .ok(response):
                        return response
                    default:
                        try throwUnexpectedResponseStatus(
                            expectedStatus: "ok",
                            response: self
                        )
                    }
                }
            }
            internal struct Unauthorized: Sendable, Hashable {
                /// Creates a new `Unauthorized`.
                internal init() {}
            }
            /// Unauthorized.
            ///
            /// - Remark: Generated from `#/paths//repos/{owner}/{repo}/milestones/get(listMilestones)/responses/401`.
            ///
            /// HTTP response code: `401 unauthorized`.
            case unauthorized(Operations.ListMilestones.Output.Unauthorized)
            /// Unauthorized.
            ///
            /// - Remark: Generated from `#/paths//repos/{owner}/{repo}/milestones/get(listMilestones)/responses/401`.
            ///
            /// HTTP response code: `401 unauthorized`.
            internal static var unauthorized: Self {
                .unauthorized(.init())
            }
            /// The associated value of the enum case if `self` is `.unauthorized`.
            ///
            /// - Throws: An error if `self` is not `.unauthorized`.
            /// - SeeAlso: `.unauthorized`.
            internal var unauthorized: Operations.ListMilestones.Output.Unauthorized {
                get throws {
                    switch self {
                    case let .unauthorized(response):
                        return response
                    default:
                        try throwUnexpectedResponseStatus(
                            expectedStatus: "unauthorized",
                            response: self
                        )
                    }
                }
            }
            /// Undocumented response.
            ///
            /// A response with a code that is not documented in the OpenAPI document.
            case undocumented(statusCode: Swift.Int, OpenAPIRuntime.UndocumentedPayload)
        }
    }
    /// Create a Milestone
    ///
    /// Creates a new milestone in the specified repository.
    ///
    /// - Remark: HTTP `POST /repos/{owner}/{repo}/milestones`.
    /// - Remark: Generated from `#/paths//repos/{owner}/{repo}/milestones/post(createMilestone)`.
    internal enum CreateMilestone {
        internal static let id: Swift.String = "createMilestone"
        internal struct Input: Sendable, Hashable {
            /// - Remark: Generated from `#/paths/repos/{owner}/{repo}/milestones/POST/path`.
            internal struct Path: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/repos/{owner}/{repo}/milestones/POST/path/owner`.
                internal var owner: Swift.String
                /// - Remark: Generated from `#/paths/repos/{owner}/{repo}/milestones/POST/path/repo`.
                internal var repo: Swift.String
                /// Creates a new `Path`.
                ///
                /// - Parameters:
                ///   - owner:
                ///   - repo:
                internal init(
                    owner: Swift.String,
                    repo: Swift.String
                ) {
                    self.owner = owner
                    self.repo = repo
                }
            }
            internal var path: Operations.CreateMilestone.Input.Path
            /// - Remark: Generated from `#/paths/repos/{owner}/{repo}/milestones/POST/requestBody`.
            internal enum Body: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/repos/{owner}/{repo}/milestones/POST/requestBody/json`.
                internal struct JsonPayload: Codable, Hashable, Sendable {
                    /// - Remark: Generated from `#/paths/repos/{owner}/{repo}/milestones/POST/requestBody/json/title`.
                    internal var title: Swift.String?
                    /// - Remark: Generated from `#/paths/repos/{owner}/{repo}/milestones/POST/requestBody/json/state`.
                    internal enum StatePayload: String, Codable, Hashable, Sendable, CaseIterable {
                        case open = "open"
                        case closed = "closed"
                    }
                    /// - Remark: Generated from `#/paths/repos/{owner}/{repo}/milestones/POST/requestBody/json/state`.
                    internal var state: Operations.CreateMilestone.Input.Body.JsonPayload.StatePayload?
                    /// - Remark: Generated from `#/paths/repos/{owner}/{repo}/milestones/POST/requestBody/json/description`.
                    internal var description: Swift.String?
                    /// - Remark: Generated from `#/paths/repos/{owner}/{repo}/milestones/POST/requestBody/json/due_on`.
                    internal var dueOn: Foundation.Date?
                    /// Creates a new `JsonPayload`.
                    ///
                    /// - Parameters:
                    ///   - title:
                    ///   - state:
                    ///   - description:
                    ///   - dueOn:
                    internal init(
                        title: Swift.String? = nil,
                        state: Operations.CreateMilestone.Input.Body.JsonPayload.StatePayload? = nil,
                        description: Swift.String? = nil,
                        dueOn: Foundation.Date? = nil
                    ) {
                        self.title = title
                        self.state = state
                        self.description = description
                        self.dueOn = dueOn
                    }
                    internal enum CodingKeys: String, CodingKey {
                        case title
                        case state
                        case description
                        case dueOn = "due_on"
                    }
                }
                /// - Remark: Generated from `#/paths/repos/{owner}/{repo}/milestones/POST/requestBody/content/application\/json`.
                case json(Operations.CreateMilestone.Input.Body.JsonPayload)
            }
            internal var body: Operations.CreateMilestone.Input.Body
            /// Creates a new `Input`.
            ///
            /// - Parameters:
            ///   - path:
            ///   - body:
            internal init(
                path: Operations.CreateMilestone.Input.Path,
                body: Operations.CreateMilestone.Input.Body
            ) {
                self.path = path
                self.body = body
            }
        }
        internal enum Output: Sendable, Hashable {
            internal struct Created: Sendable, Hashable {
                /// Creates a new `Created`.
                internal init() {}
            }
            /// Milestone created successfully.
            ///
            /// - Remark: Generated from `#/paths//repos/{owner}/{repo}/milestones/post(createMilestone)/responses/201`.
            ///
            /// HTTP response code: `201 created`.
            case created(Operations.CreateMilestone.Output.Created)
            /// Milestone created successfully.
            ///
            /// - Remark: Generated from `#/paths//repos/{owner}/{repo}/milestones/post(createMilestone)/responses/201`.
            ///
            /// HTTP response code: `201 created`.
            internal static var created: Self {
                .created(.init())
            }
            /// The associated value of the enum case if `self` is `.created`.
            ///
            /// - Throws: An error if `self` is not `.created`.
            /// - SeeAlso: `.created`.
            internal var created: Operations.CreateMilestone.Output.Created {
                get throws {
                    switch self {
                    case let .created(response):
                        return response
                    default:
                        try throwUnexpectedResponseStatus(
                            expectedStatus: "created",
                            response: self
                        )
                    }
                }
            }
            internal struct Unauthorized: Sendable, Hashable {
                /// Creates a new `Unauthorized`.
                internal init() {}
            }
            /// Unauthorized.
            ///
            /// - Remark: Generated from `#/paths//repos/{owner}/{repo}/milestones/post(createMilestone)/responses/401`.
            ///
            /// HTTP response code: `401 unauthorized`.
            case unauthorized(Operations.CreateMilestone.Output.Unauthorized)
            /// Unauthorized.
            ///
            /// - Remark: Generated from `#/paths//repos/{owner}/{repo}/milestones/post(createMilestone)/responses/401`.
            ///
            /// HTTP response code: `401 unauthorized`.
            internal static var unauthorized: Self {
                .unauthorized(.init())
            }
            /// The associated value of the enum case if `self` is `.unauthorized`.
            ///
            /// - Throws: An error if `self` is not `.unauthorized`.
            /// - SeeAlso: `.unauthorized`.
            internal var unauthorized: Operations.CreateMilestone.Output.Unauthorized {
                get throws {
                    switch self {
                    case let .unauthorized(response):
                        return response
                    default:
                        try throwUnexpectedResponseStatus(
                            expectedStatus: "unauthorized",
                            response: self
                        )
                    }
                }
            }
            internal struct UnprocessableContent: Sendable, Hashable {
                /// Creates a new `UnprocessableContent`.
                internal init() {}
            }
            /// Validation failed.
            ///
            /// - Remark: Generated from `#/paths//repos/{owner}/{repo}/milestones/post(createMilestone)/responses/422`.
            ///
            /// HTTP response code: `422 unprocessableContent`.
            case unprocessableContent(Operations.CreateMilestone.Output.UnprocessableContent)
            /// Validation failed.
            ///
            /// - Remark: Generated from `#/paths//repos/{owner}/{repo}/milestones/post(createMilestone)/responses/422`.
            ///
            /// HTTP response code: `422 unprocessableContent`.
            internal static var unprocessableContent: Self {
                .unprocessableContent(.init())
            }
            /// The associated value of the enum case if `self` is `.unprocessableContent`.
            ///
            /// - Throws: An error if `self` is not `.unprocessableContent`.
            /// - SeeAlso: `.unprocessableContent`.
            internal var unprocessableContent: Operations.CreateMilestone.Output.UnprocessableContent {
                get throws {
                    switch self {
                    case let .unprocessableContent(response):
                        return response
                    default:
                        try throwUnexpectedResponseStatus(
                            expectedStatus: "unprocessableContent",
                            response: self
                        )
                    }
                }
            }
            /// Undocumented response.
            ///
            /// A response with a code that is not documented in the OpenAPI document.
            case undocumented(statusCode: Swift.Int, OpenAPIRuntime.UndocumentedPayload)
        }
    }
    /// Get a Milestone
    ///
    /// Retrieves details of a specific milestone.
    ///
    /// - Remark: HTTP `GET /repos/{owner}/{repo}/milestones/{milestone_number}`.
    /// - Remark: Generated from `#/paths//repos/{owner}/{repo}/milestones/{milestone_number}/get(getMilestone)`.
    internal enum GetMilestone {
        internal static let id: Swift.String = "getMilestone"
        internal struct Input: Sendable, Hashable {
            /// - Remark: Generated from `#/paths/repos/{owner}/{repo}/milestones/{milestone_number}/GET/path`.
            internal struct Path: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/repos/{owner}/{repo}/milestones/{milestone_number}/GET/path/owner`.
                internal var owner: Swift.String
                /// - Remark: Generated from `#/paths/repos/{owner}/{repo}/milestones/{milestone_number}/GET/path/repo`.
                internal var repo: Swift.String
                /// - Remark: Generated from `#/paths/repos/{owner}/{repo}/milestones/{milestone_number}/GET/path/milestone_number`.
                internal var milestoneNumber: Swift.Int
                /// Creates a new `Path`.
                ///
                /// - Parameters:
                ///   - owner:
                ///   - repo:
                ///   - milestoneNumber:
                internal init(
                    owner: Swift.String,
                    repo: Swift.String,
                    milestoneNumber: Swift.Int
                ) {
                    self.owner = owner
                    self.repo = repo
                    self.milestoneNumber = milestoneNumber
                }
            }
            internal var path: Operations.GetMilestone.Input.Path
            /// Creates a new `Input`.
            ///
            /// - Parameters:
            ///   - path:
            internal init(path: Operations.GetMilestone.Input.Path) {
                self.path = path
            }
        }
        internal enum Output: Sendable, Hashable {
            internal struct Ok: Sendable, Hashable {
                /// Creates a new `Ok`.
                internal init() {}
            }
            /// Milestone retrieved successfully.
            ///
            /// - Remark: Generated from `#/paths//repos/{owner}/{repo}/milestones/{milestone_number}/get(getMilestone)/responses/200`.
            ///
            /// HTTP response code: `200 ok`.
            case ok(Operations.GetMilestone.Output.Ok)
            /// Milestone retrieved successfully.
            ///
            /// - Remark: Generated from `#/paths//repos/{owner}/{repo}/milestones/{milestone_number}/get(getMilestone)/responses/200`.
            ///
            /// HTTP response code: `200 ok`.
            internal static var ok: Self {
                .ok(.init())
            }
            /// The associated value of the enum case if `self` is `.ok`.
            ///
            /// - Throws: An error if `self` is not `.ok`.
            /// - SeeAlso: `.ok`.
            internal var ok: Operations.GetMilestone.Output.Ok {
                get throws {
                    switch self {
                    case let .ok(response):
                        return response
                    default:
                        try throwUnexpectedResponseStatus(
                            expectedStatus: "ok",
                            response: self
                        )
                    }
                }
            }
            internal struct Unauthorized: Sendable, Hashable {
                /// Creates a new `Unauthorized`.
                internal init() {}
            }
            /// Unauthorized.
            ///
            /// - Remark: Generated from `#/paths//repos/{owner}/{repo}/milestones/{milestone_number}/get(getMilestone)/responses/401`.
            ///
            /// HTTP response code: `401 unauthorized`.
            case unauthorized(Operations.GetMilestone.Output.Unauthorized)
            /// Unauthorized.
            ///
            /// - Remark: Generated from `#/paths//repos/{owner}/{repo}/milestones/{milestone_number}/get(getMilestone)/responses/401`.
            ///
            /// HTTP response code: `401 unauthorized`.
            internal static var unauthorized: Self {
                .unauthorized(.init())
            }
            /// The associated value of the enum case if `self` is `.unauthorized`.
            ///
            /// - Throws: An error if `self` is not `.unauthorized`.
            /// - SeeAlso: `.unauthorized`.
            internal var unauthorized: Operations.GetMilestone.Output.Unauthorized {
                get throws {
                    switch self {
                    case let .unauthorized(response):
                        return response
                    default:
                        try throwUnexpectedResponseStatus(
                            expectedStatus: "unauthorized",
                            response: self
                        )
                    }
                }
            }
            internal struct NotFound: Sendable, Hashable {
                /// Creates a new `NotFound`.
                internal init() {}
            }
            /// Milestone not found.
            ///
            /// - Remark: Generated from `#/paths//repos/{owner}/{repo}/milestones/{milestone_number}/get(getMilestone)/responses/404`.
            ///
            /// HTTP response code: `404 notFound`.
            case notFound(Operations.GetMilestone.Output.NotFound)
            /// Milestone not found.
            ///
            /// - Remark: Generated from `#/paths//repos/{owner}/{repo}/milestones/{milestone_number}/get(getMilestone)/responses/404`.
            ///
            /// HTTP response code: `404 notFound`.
            internal static var notFound: Self {
                .notFound(.init())
            }
            /// The associated value of the enum case if `self` is `.notFound`.
            ///
            /// - Throws: An error if `self` is not `.notFound`.
            /// - SeeAlso: `.notFound`.
            internal var notFound: Operations.GetMilestone.Output.NotFound {
                get throws {
                    switch self {
                    case let .notFound(response):
                        return response
                    default:
                        try throwUnexpectedResponseStatus(
                            expectedStatus: "notFound",
                            response: self
                        )
                    }
                }
            }
            /// Undocumented response.
            ///
            /// A response with a code that is not documented in the OpenAPI document.
            case undocumented(statusCode: Swift.Int, OpenAPIRuntime.UndocumentedPayload)
        }
    }
    /// Update a Milestone
    ///
    /// Updates an existing milestone.
    ///
    /// - Remark: HTTP `PATCH /repos/{owner}/{repo}/milestones/{milestone_number}`.
    /// - Remark: Generated from `#/paths//repos/{owner}/{repo}/milestones/{milestone_number}/patch(updateMilestone)`.
    internal enum UpdateMilestone {
        internal static let id: Swift.String = "updateMilestone"
        internal struct Input: Sendable, Hashable {
            /// - Remark: Generated from `#/paths/repos/{owner}/{repo}/milestones/{milestone_number}/PATCH/path`.
            internal struct Path: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/repos/{owner}/{repo}/milestones/{milestone_number}/PATCH/path/owner`.
                internal var owner: Swift.String
                /// - Remark: Generated from `#/paths/repos/{owner}/{repo}/milestones/{milestone_number}/PATCH/path/repo`.
                internal var repo: Swift.String
                /// - Remark: Generated from `#/paths/repos/{owner}/{repo}/milestones/{milestone_number}/PATCH/path/milestone_number`.
                internal var milestoneNumber: Swift.Int
                /// Creates a new `Path`.
                ///
                /// - Parameters:
                ///   - owner:
                ///   - repo:
                ///   - milestoneNumber:
                internal init(
                    owner: Swift.String,
                    repo: Swift.String,
                    milestoneNumber: Swift.Int
                ) {
                    self.owner = owner
                    self.repo = repo
                    self.milestoneNumber = milestoneNumber
                }
            }
            internal var path: Operations.UpdateMilestone.Input.Path
            /// - Remark: Generated from `#/paths/repos/{owner}/{repo}/milestones/{milestone_number}/PATCH/requestBody`.
            internal enum Body: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/repos/{owner}/{repo}/milestones/{milestone_number}/PATCH/requestBody/json`.
                internal struct JsonPayload: Codable, Hashable, Sendable {
                    /// - Remark: Generated from `#/paths/repos/{owner}/{repo}/milestones/{milestone_number}/PATCH/requestBody/json/title`.
                    internal var title: Swift.String?
                    /// - Remark: Generated from `#/paths/repos/{owner}/{repo}/milestones/{milestone_number}/PATCH/requestBody/json/state`.
                    internal enum StatePayload: String, Codable, Hashable, Sendable, CaseIterable {
                        case open = "open"
                        case closed = "closed"
                    }
                    /// - Remark: Generated from `#/paths/repos/{owner}/{repo}/milestones/{milestone_number}/PATCH/requestBody/json/state`.
                    internal var state: Operations.UpdateMilestone.Input.Body.JsonPayload.StatePayload?
                    /// - Remark: Generated from `#/paths/repos/{owner}/{repo}/milestones/{milestone_number}/PATCH/requestBody/json/description`.
                    internal var description: Swift.String?
                    /// - Remark: Generated from `#/paths/repos/{owner}/{repo}/milestones/{milestone_number}/PATCH/requestBody/json/due_on`.
                    internal var dueOn: Foundation.Date?
                    /// Creates a new `JsonPayload`.
                    ///
                    /// - Parameters:
                    ///   - title:
                    ///   - state:
                    ///   - description:
                    ///   - dueOn:
                    internal init(
                        title: Swift.String? = nil,
                        state: Operations.UpdateMilestone.Input.Body.JsonPayload.StatePayload? = nil,
                        description: Swift.String? = nil,
                        dueOn: Foundation.Date? = nil
                    ) {
                        self.title = title
                        self.state = state
                        self.description = description
                        self.dueOn = dueOn
                    }
                    internal enum CodingKeys: String, CodingKey {
                        case title
                        case state
                        case description
                        case dueOn = "due_on"
                    }
                }
                /// - Remark: Generated from `#/paths/repos/{owner}/{repo}/milestones/{milestone_number}/PATCH/requestBody/content/application\/json`.
                case json(Operations.UpdateMilestone.Input.Body.JsonPayload)
            }
            internal var body: Operations.UpdateMilestone.Input.Body
            /// Creates a new `Input`.
            ///
            /// - Parameters:
            ///   - path:
            ///   - body:
            internal init(
                path: Operations.UpdateMilestone.Input.Path,
                body: Operations.UpdateMilestone.Input.Body
            ) {
                self.path = path
                self.body = body
            }
        }
        internal enum Output: Sendable, Hashable {
            internal struct Ok: Sendable, Hashable {
                /// Creates a new `Ok`.
                internal init() {}
            }
            /// Milestone updated successfully.
            ///
            /// - Remark: Generated from `#/paths//repos/{owner}/{repo}/milestones/{milestone_number}/patch(updateMilestone)/responses/200`.
            ///
            /// HTTP response code: `200 ok`.
            case ok(Operations.UpdateMilestone.Output.Ok)
            /// Milestone updated successfully.
            ///
            /// - Remark: Generated from `#/paths//repos/{owner}/{repo}/milestones/{milestone_number}/patch(updateMilestone)/responses/200`.
            ///
            /// HTTP response code: `200 ok`.
            internal static var ok: Self {
                .ok(.init())
            }
            /// The associated value of the enum case if `self` is `.ok`.
            ///
            /// - Throws: An error if `self` is not `.ok`.
            /// - SeeAlso: `.ok`.
            internal var ok: Operations.UpdateMilestone.Output.Ok {
                get throws {
                    switch self {
                    case let .ok(response):
                        return response
                    default:
                        try throwUnexpectedResponseStatus(
                            expectedStatus: "ok",
                            response: self
                        )
                    }
                }
            }
            internal struct Unauthorized: Sendable, Hashable {
                /// Creates a new `Unauthorized`.
                internal init() {}
            }
            /// Unauthorized.
            ///
            /// - Remark: Generated from `#/paths//repos/{owner}/{repo}/milestones/{milestone_number}/patch(updateMilestone)/responses/401`.
            ///
            /// HTTP response code: `401 unauthorized`.
            case unauthorized(Operations.UpdateMilestone.Output.Unauthorized)
            /// Unauthorized.
            ///
            /// - Remark: Generated from `#/paths//repos/{owner}/{repo}/milestones/{milestone_number}/patch(updateMilestone)/responses/401`.
            ///
            /// HTTP response code: `401 unauthorized`.
            internal static var unauthorized: Self {
                .unauthorized(.init())
            }
            /// The associated value of the enum case if `self` is `.unauthorized`.
            ///
            /// - Throws: An error if `self` is not `.unauthorized`.
            /// - SeeAlso: `.unauthorized`.
            internal var unauthorized: Operations.UpdateMilestone.Output.Unauthorized {
                get throws {
                    switch self {
                    case let .unauthorized(response):
                        return response
                    default:
                        try throwUnexpectedResponseStatus(
                            expectedStatus: "unauthorized",
                            response: self
                        )
                    }
                }
            }
            internal struct NotFound: Sendable, Hashable {
                /// Creates a new `NotFound`.
                internal init() {}
            }
            /// Milestone not found.
            ///
            /// - Remark: Generated from `#/paths//repos/{owner}/{repo}/milestones/{milestone_number}/patch(updateMilestone)/responses/404`.
            ///
            /// HTTP response code: `404 notFound`.
            case notFound(Operations.UpdateMilestone.Output.NotFound)
            /// Milestone not found.
            ///
            /// - Remark: Generated from `#/paths//repos/{owner}/{repo}/milestones/{milestone_number}/patch(updateMilestone)/responses/404`.
            ///
            /// HTTP response code: `404 notFound`.
            internal static var notFound: Self {
                .notFound(.init())
            }
            /// The associated value of the enum case if `self` is `.notFound`.
            ///
            /// - Throws: An error if `self` is not `.notFound`.
            /// - SeeAlso: `.notFound`.
            internal var notFound: Operations.UpdateMilestone.Output.NotFound {
                get throws {
                    switch self {
                    case let .notFound(response):
                        return response
                    default:
                        try throwUnexpectedResponseStatus(
                            expectedStatus: "notFound",
                            response: self
                        )
                    }
                }
            }
            /// Undocumented response.
            ///
            /// A response with a code that is not documented in the OpenAPI document.
            case undocumented(statusCode: Swift.Int, OpenAPIRuntime.UndocumentedPayload)
        }
    }
    /// Delete a Milestone
    ///
    /// Deletes a specific milestone.
    ///
    /// - Remark: HTTP `DELETE /repos/{owner}/{repo}/milestones/{milestone_number}`.
    /// - Remark: Generated from `#/paths//repos/{owner}/{repo}/milestones/{milestone_number}/delete(deleteMilestone)`.
    internal enum DeleteMilestone {
        internal static let id: Swift.String = "deleteMilestone"
        internal struct Input: Sendable, Hashable {
            /// - Remark: Generated from `#/paths/repos/{owner}/{repo}/milestones/{milestone_number}/DELETE/path`.
            internal struct Path: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/repos/{owner}/{repo}/milestones/{milestone_number}/DELETE/path/owner`.
                internal var owner: Swift.String
                /// - Remark: Generated from `#/paths/repos/{owner}/{repo}/milestones/{milestone_number}/DELETE/path/repo`.
                internal var repo: Swift.String
                /// - Remark: Generated from `#/paths/repos/{owner}/{repo}/milestones/{milestone_number}/DELETE/path/milestone_number`.
                internal var milestoneNumber: Swift.Int
                /// Creates a new `Path`.
                ///
                /// - Parameters:
                ///   - owner:
                ///   - repo:
                ///   - milestoneNumber:
                internal init(
                    owner: Swift.String,
                    repo: Swift.String,
                    milestoneNumber: Swift.Int
                ) {
                    self.owner = owner
                    self.repo = repo
                    self.milestoneNumber = milestoneNumber
                }
            }
            internal var path: Operations.DeleteMilestone.Input.Path
            /// Creates a new `Input`.
            ///
            /// - Parameters:
            ///   - path:
            internal init(path: Operations.DeleteMilestone.Input.Path) {
                self.path = path
            }
        }
        internal enum Output: Sendable, Hashable {
            internal struct NoContent: Sendable, Hashable {
                /// Creates a new `NoContent`.
                internal init() {}
            }
            /// Milestone deleted successfully.
            ///
            /// - Remark: Generated from `#/paths//repos/{owner}/{repo}/milestones/{milestone_number}/delete(deleteMilestone)/responses/204`.
            ///
            /// HTTP response code: `204 noContent`.
            case noContent(Operations.DeleteMilestone.Output.NoContent)
            /// Milestone deleted successfully.
            ///
            /// - Remark: Generated from `#/paths//repos/{owner}/{repo}/milestones/{milestone_number}/delete(deleteMilestone)/responses/204`.
            ///
            /// HTTP response code: `204 noContent`.
            internal static var noContent: Self {
                .noContent(.init())
            }
            /// The associated value of the enum case if `self` is `.noContent`.
            ///
            /// - Throws: An error if `self` is not `.noContent`.
            /// - SeeAlso: `.noContent`.
            internal var noContent: Operations.DeleteMilestone.Output.NoContent {
                get throws {
                    switch self {
                    case let .noContent(response):
                        return response
                    default:
                        try throwUnexpectedResponseStatus(
                            expectedStatus: "noContent",
                            response: self
                        )
                    }
                }
            }
            internal struct Unauthorized: Sendable, Hashable {
                /// Creates a new `Unauthorized`.
                internal init() {}
            }
            /// Unauthorized.
            ///
            /// - Remark: Generated from `#/paths//repos/{owner}/{repo}/milestones/{milestone_number}/delete(deleteMilestone)/responses/401`.
            ///
            /// HTTP response code: `401 unauthorized`.
            case unauthorized(Operations.DeleteMilestone.Output.Unauthorized)
            /// Unauthorized.
            ///
            /// - Remark: Generated from `#/paths//repos/{owner}/{repo}/milestones/{milestone_number}/delete(deleteMilestone)/responses/401`.
            ///
            /// HTTP response code: `401 unauthorized`.
            internal static var unauthorized: Self {
                .unauthorized(.init())
            }
            /// The associated value of the enum case if `self` is `.unauthorized`.
            ///
            /// - Throws: An error if `self` is not `.unauthorized`.
            /// - SeeAlso: `.unauthorized`.
            internal var unauthorized: Operations.DeleteMilestone.Output.Unauthorized {
                get throws {
                    switch self {
                    case let .unauthorized(response):
                        return response
                    default:
                        try throwUnexpectedResponseStatus(
                            expectedStatus: "unauthorized",
                            response: self
                        )
                    }
                }
            }
            internal struct NotFound: Sendable, Hashable {
                /// Creates a new `NotFound`.
                internal init() {}
            }
            /// Milestone not found.
            ///
            /// - Remark: Generated from `#/paths//repos/{owner}/{repo}/milestones/{milestone_number}/delete(deleteMilestone)/responses/404`.
            ///
            /// HTTP response code: `404 notFound`.
            case notFound(Operations.DeleteMilestone.Output.NotFound)
            /// Milestone not found.
            ///
            /// - Remark: Generated from `#/paths//repos/{owner}/{repo}/milestones/{milestone_number}/delete(deleteMilestone)/responses/404`.
            ///
            /// HTTP response code: `404 notFound`.
            internal static var notFound: Self {
                .notFound(.init())
            }
            /// The associated value of the enum case if `self` is `.notFound`.
            ///
            /// - Throws: An error if `self` is not `.notFound`.
            /// - SeeAlso: `.notFound`.
            internal var notFound: Operations.DeleteMilestone.Output.NotFound {
                get throws {
                    switch self {
                    case let .notFound(response):
                        return response
                    default:
                        try throwUnexpectedResponseStatus(
                            expectedStatus: "notFound",
                            response: self
                        )
                    }
                }
            }
            /// Undocumented response.
            ///
            /// A response with a code that is not documented in the OpenAPI document.
            case undocumented(statusCode: Swift.Int, OpenAPIRuntime.UndocumentedPayload)
        }
    }
}
